version: 0.0
os: linux

files:
  - source: /
    destination: /opt/ecommerce-app

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
